// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ContainerList():Promise<Array<types.ContainerSummary>>;

export function StartContainer(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;
