// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerList() {
  return window['go']['services']['containerService']['ContainerList']();
}

export function DeleteContainer(arg1) {
  return window['go']['services']['containerService']['DeleteContainer'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['services']['containerService']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['services']['containerService']['StopContainer'](arg1);
}
