// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DeleteImage(arg1:string,arg2:string):Promise<boolean>;

export function ImageList():Promise<Array<types.ImageSummary>>;
