// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteImage(arg1) {
  return window['go']['services']['imageService']['DeleteImage'](arg1);
}

export function ImageList() {
  return window['go']['services']['imageService']['ImageList']();
}
