// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DockerInfo():Promise<types.VersionInfo>;

export function ProgramInfo():Promise<types.Info>;
