// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DockerInfo() {
  return window['go']['services']['programService']['DockerInfo']();
}

export function ProgramInfo() {
  return window['go']['services']['programService']['ProgramInfo']();
}
